### ISSUE TITLE
help about my_bcast.c

### ISSUE THREAD

**Issue by icenaive** [wesleykendall/mpitutorial#55]
I ran the broadcast routine，But sometimes it doesn't output the prompt for all the processes to receive the data, and sometimes it outputs the prompt for all of them. the prompt is `printf("Process %d received data from root process in my_bcast\n", world_rank);`  I hope to get your help about this. thank you.

**Comment by wesbland** [comment]
Can you please post your code?

**Comment by icenaive** [comment]
[my_bcast.txt](https://github.com/wesleykendall/mpitutorial/files/3948005/my_bcast.txt)
this is my code.

**Comment by wesbland** [comment]
I'm not exactly sure what the problem is since I can't replicate it:

```
$ mpiexec -n 4 ./a.out
Process 0 broadcasting data 100
Process 0 broadcasting data to 1 in my_bcast
Process 0 broadcasting data to 2 in my_bcast
Process 0 broadcasting data to 3 in my_bcast
Process 1 received data from root process in my_bcast
Process 1 received data 100 from root process in main
Process 2 received data from root process in my_bcast
Process 2 received data 100 from root process in main
Process 3 received data from root process in my_bcast
Process 3 received data 100 from root process in main
```

However, my guess is that you're seeing this because you're missing `MPI_Finalize();` at the end of your code. Particularly if you're missing text from processes other than rank 0, it could be that `stdout` didn't get flushed before the app shut down since you didn't give the MPI library a chance to do so.

While `MPI_Finalize` is sort of optional in the sense that your application _usually_ will work fine without it, there are times where not calling it prevents MPI form being able to do the right thing before shutting down.
